DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  dob DATE NOT NULL
);


DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  fName VARCHAR(250) NOT NULL,
  lName VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS EVENT;

CREATE TABLE EVENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  startDate DateTime NOT NULL,
  endDate DateTime NOT NULL
);